baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Abel's Blog"
theme = "paper"
paginate = 10
paginatePath = '.'

DefaultContentLanguage = "en"
enableInlineShortcodes = true

[params]
  # color style
  color = 'gray'

  rss = true

  # misc
  disableHLJS = true                        # disable highlight.js
  monoDarkIcon = true

  enableEmoji = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10